// OBJETOS LITERALES !== OBJETOS DE LA PROGRAMACION ORIENTADA A
// OBJETOS

// TAMBIEN SE LES CONOCE EN OTROS LENGUAJES DE PROGRAMACION 
// COMO MAPAS/MAPS, O ARREGLOS ASOCIATIVOS/ASOCIATIVE ARRAYS
const jaguar = {
  nombre: "Jaguar",
  color: "Amarillo",
};

// PARA ACCEDER A LAS PROPIEDADES DE UN OBJETO,
// PUEDO USAR LA NOTACION DE PUNTO/ DOT NOTATION
console.log("NOTACION DE PUNTO", jaguar.nombre);
console.log("NOTACION DE PUNTO", jaguar.color);

// TAMBIEN PUEDES ACCEDER A SUS VALORES, MEDIANTE LA
// NOTACION DE CORCHETES CUADRADOS/SQUARE BRACKETS NOTATION
console.log("NOTACION DE CORCH. CUADRADOS", jaguar["nombre"]);
console.log("NOTACION DE CORCH. CUADRADOS", jaguar["color"]);
