// TENEMOS 3 SECCIONES,
// LA INICIALIZACION DE UNA VARIABLE DE CONTROL,
// UNA CONDICION RELACIONADA A ESA VARIABLE,
// UN INCREMENTO A ESA MISMA VARIABLE

for (let i = 0; i < 30; i++) {
  console.log(i);
}